name: Generate new forecast image

on:
  workflow_dispatch:
  schedule:
    - cron: '6 10 * * *'

jobs:
  generate_image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python weather_runner.py
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        DALLE3_COOKIE: ${{ secrets.DALLE3_COOKIE }}
        GMAPS_API: ${{ secrets.GMAPS_API }}

    - name: Commit and push if it changed
      run: | 
        git config user.name "JonathanGrant"
        git config user.email "jonathanallengrant@gmail.com"
        git add -A
        git commit -m "Auto update image"
        git push https://${{ secrets.GH_TOKEN }}@github.com/JonathanGrant/WeatherBei.git
